import type { Metadata } from "next";
import "../globals.css";
import { notFound } from "next/navigation";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { AuthProvider } from "@/providers/AuthProvider";
import { QueryProvider } from "@/providers/QueryProvider";
import { Toaster } from "@/components/ui/toaster";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

const locales = ["en", "vi"];

export default async function RootLayout({
 children,
 params,
}: Readonly<{
 children: React.ReactNode;
 params: { locale: string };
}>) {
 const { locale } = await params;

 const isValidLocale = locales.some((cur) => cur === locale);
 if (!isValidLocale) notFound();

 const messages = await getMessages();

 return (
  <html lang={locale} suppressHydrationWarning>
   <body className={``}>
    <NextIntlClientProvider locale={locale} messages={messages}>
     <AuthProvider>
      <QueryProvider>
       <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
       >
        <Toaster />
        {children}
       </ThemeProvider>
      </QueryProvider>
     </AuthProvider>
    </NextIntlClientProvider>
   </body>
  </html>
 );
}
