import type { Metadata } from "next";
import "../globals.css";
import { notFound } from "next/navigation";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { AuthProvider } from "@/providers/AuthProvider";
import { QueryProvider } from "@/providers/QueryProvider";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

const locales = ["en", "te"];

export default async function RootLayout({
 children,
 params: { locale },
}: Readonly<{
 children: React.ReactNode;
 params: { locale: string };
}>) {
 const isValidLocale = locales.some((cur) => cur === locale);
 if (!isValidLocale) notFound();

 //@ts-ignore
 const messages = await getMessages(locale);
 return (
  <html lang={locale} suppressHydrationWarning>
   <body className={`antialiased`}>
    <NextIntlClientProvider locale={locale} messages={messages}>
     <AuthProvider>
      <QueryProvider>
       <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
       >
        {/* <Toaster /> */}
        {children}
       </ThemeProvider>
      </QueryProvider>
     </AuthProvider>
    </NextIntlClientProvider>
   </body>
  </html>
 );
}
